# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 9000:8080

  store-client:
    build: store-client
    ports:
      - 8080:8080

  store-api:
    build: store-api
    ports: 
      - 8090:8080